controller_list:
  - name: "blue_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

blue_arm_controller:
  type: velocity_controllers/JointTrajectoryController
  # type: velocity_controllers/JointVelocityController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 0.1, goal: 0.1}
      joint_2: {trajectory: 0.1, goal: 0.1}
      joint_3: {trajectory: 0.1, goal: 0.1}
      joint_4: {trajectory: 0.1, goal: 0.1}
      joint_5: {trajectory: 0.1, goal: 0.1}
      joint_6: {trajectory: 0.1, goal: 0.1}
      joint_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
    joint_1:
      p: 600
      d: 0
      i: 0.0
    joint_2:
      p: 600
      d: 0.0
      i: 0.0
    joint_3:
      p: 320
      d: 0.0
      i: 0.0
    joint_4:
      p: 320
      d: 0.0
      i: 0.0
    joint_5:
      p: 320
      d: 0.0
      i: 0.0
    joint_6:
      p: 200
      d: 0.0
      i: 0.0
    joint_7:
      p: 200
      d: 0.0
      i: 0.0

gazebo_ros_control:
  pid_gains:
    joint_1: {p: 15.0, i: 0.0, d: 0.0}
    joint_2: {p: 15.0, i: 0.0, d: 0.0}
    joint_3: {p: 8.0, i: 0.0, d: 0.0}
    joint_4: {p: 8.0, i: 0.0, d: 0.0}
    joint_5: {p: 8.0, i: 0.0, d: 0.0}
    joint_6: {p: 5.0, i: 0.0, d: 0.0}
    joint_7: {p: 5.0, i: 0.0, d: 0.0}